### ISSUE TITLE
授权失败

### ISSUE THREAD

**Issue by yeshiyuan00** [hanks-zyh/Conquer#4]
qq和微博登录都不行，总是提示登录授权失败（错误码:110406)

**Comment by hanks-zyh** [comment]
@yeshiyuan00  授权登录的代码主要都在 LoginActivity 中，你可以通过以下方法解决：
1. 自己申请qq或者微博的key，然后替换
2. 修改代码，跳过qq或者微博授权逻辑，模拟一个用户来登录

建议使用第一种
后台用的Bmob，也建议自己申请一个

**Comment by yeshiyuan00** [comment]
@hanks-zyh 谢谢，解决了！
